repos:
  - repo: local
    hooks:
      - id: hugo-build
        name: hugo build
        entry: hugo
        args: [--minify]
        language: system
        types: [file]
        pass_filenames: false
        always_run: true
