theme = "blowfish"
baseURL = "https://lvlcn-t.dev"
languageCode = "en"
defaultContentLanguage = "en"
title = "lvlcn-t"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  colorScheme = "ocean"
  defaultAppearance = "dark"
  autoSwitchAppearance = true
  enableSearch = false
  enableCodeCopy = false
  description = "Tom's personal landing page"

  [params.header]
    layout = "fixed"

  [params.footer]
    showMenu = false
    showCopyright = true
    showThemeAttribution = false
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = "profile"
    showRecent = false

  [params.author]
    name = "Tom Vendolsky"
    image = "img/profile.jpg"
    headline = "Platform Engineer"
    bio = "Platform engineer focused on cloud and automation"
    links = [
      { github = "https://github.com/lvlcn-t" },
      { linkedin = "https://linkedin.com/in/tom-vendolsky" },
      { bluesky = "https://bsky.app/profile/lvlcn-t.dev" }
    ]
